eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true
spring:
  datasource:
      hikari:
          connection-test-query: SELECT 1 FROM DUAL
          minimum-idle: 1
          maximum-pool-size: 5
          pool-name: yourPoolName
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.31.9.243:3306/liquidstudio_microservice_demo
      username: root
      password: mycai111
      type: com.zaxxer.hikari.HikariDataSource
